
const ERR_POST_UNKNOWN = {err:0, msg:"error post unknown"};
const ERR_LOGIN_ADMIN = {err:1, msg:"error incorrect admin login"};
exports.ERR_POST_UNKNOWN = ERR_POST_UNKNOWN;
exports.ERR_LOGIN_ADMIN = ERR_LOGIN_ADMIN;


const ERROR_MYSQL_POOL = "ERR MYSQL POOL";
const ERROR_MYSQL_CONNECTION = "ERR MYSQL CONNECTION";
const ERROR_MYSQL = "ERR MYSQL";
exports.ERROR_MYSQL_POOL = ERROR_MYSQL_POOL;
exports.ERROR_MYSQL_CONNECTION = ERROR_MYSQL_CONNECTION;
exports.ERROR_MYSQL = ERROR_MYSQL;

const ERROR_REQ_MISSING_A_PARAMETER = "ERR REQUEST MISSING A PARAMETER";
exports.ERROR_REQ_MISSING_A_PARAMETER = ERROR_REQ_MISSING_A_PARAMETER;